In [ ]:
import pandas as pd
from textblob import TextBlob
import matplotlib.pyplot as plt

In [ ]:
import pandas as pd
import csv

# Use on_bad_lines to skip bad lines and error_bad_lines to raise an error
# The 'skip' option will skip the problematic rows.
# Other options include 'warn' to issue a warning or 'error' to raise an exception.
true_df = pd.read_csv('/content/True.csv', quoting=csv.QUOTE_MINIMAL, on_bad_lines='skip')
fake_df = pd.read_csv('/content/Fake.csv', quoting=csv.QUOTE_MINIMAL, on_bad_lines='skip')

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report
import re
import joblib
import string

In [ ]:
import pandas as pd

# The files are already extracted, so read them directly as CSV
true = pd.read_csv('/content/True.csv')
fake = pd.read_csv('/content/Fake.csv')

In [ ]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [ ]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [ ]:
true['class']=1
fake['class']=0

In [ ]:
df = pd.concat([fake,true], axis=0)

In [ ]:
df.sample(5)

,title,text,subject,date,class
15416,Saudi reopens Lebanon front in struggle with Iran,BEIRUT (Reuters) - Saudi Arabia has opened a n...,worldnews,"November 7, 2017",1
4462,Watch This 9-Year-Old Girl’s Heartbreaking Me...,"9-year-old Charlotte, North Carolina girl Zian...",News,"September 27, 2016",0
9084,JUST IN: CROOKED DOJ OFFICIAL Didn’t Reveal Th...,We ve been covering the curious case of DOJ of...,politics,14-Feb-18,0
6483,Anarchists threaten to disrupt Trump inaugurat...,WASHINGTON (Reuters) - Anarchist groups have t...,politicsNews,"January 6, 2017",1
3120,WATCH: Joy Reid HAMMERS Republicans For Wasti...,Republicans are lying when they claim to be f...,News,"January 7, 2017",0

In [ ]:
df = df.drop(["title", "subject", "date"], axis=1)

In [ ]:
df.head()

                                                text  class
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [ ]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r"\[.*?\]", "", text)
    text = re.sub(r"//W", "", text)
    text = re.sub(r"https?://\S+|www\.\S+", "", text)
    text = re.sub(r"<.*?>+", "", text)
    text = re.sub(r"[%s]" % re.escape(string.punctuation), "", text)
    text = re.sub(r"\n", "", text)
    text = re.sub(r"\w*\d\w*", "", text)
    return text

In [ ]:
df["text"] = df["text"].apply(clean_text)

In [ ]:
x = df["text"]
Y = df["class"]

In [ ]:
x_train, x_test, Y_train, Y_test = train_test_split(x, Y, test_size=0.2, random_state=42)

In [ ]:
vectorizer = TfidfVectorizer()

In [ ]:
xv_train = vectorizer.fit_transform(x_train)
xv_test = vectorizer.transform(x_test)

In [ ]:
model = LogisticRegression()
model.fit(xv_train, Y_train)

LogisticRegression()

In [ ]:
prediction = model.predict(xv_test)

In [ ]:
model.score(xv_test, Y_test)

0.9857461024498887

In [ ]:
print(classification_report(Y_test,prediction))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4733
           1       0.98      0.99      0.98      4247

    accuracy                           0.99      8980
   macro avg       0.99      0.99      0.99      8980
weighted avg       0.99      0.99      0.99      8980